# ================================================================================
# ARCHIVO 5: auth-service.yml
# ================================================================================

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: root
    password: edwinyoner

  jpa:
    hibernate:
      ddl-auto: update # En dev: update, en prod: validate

eureka:
  client:
    serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
